version: '3'
services:
  db:
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: postgres # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: postgres # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: postgres # The PostgreSQL default database (automatically created at first launch)
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - /home/ubuntu/db:/var/lib/postgresql/data
    restart: 'always'
    logging:
      driver: "json-file"
      options:
        max-size: "10k"
        max-file: "3"

  backend:
    build:
      context: ./yourthoughts
      dockerfile: Dockerfile
    ports:
      - "10000:8000"
    restart: 'always'
    command: >
      bash -c "python manage.py wait_for_db &&
               python manage.py makemigrations --settings=yourthoughts.production_settings &&
               python manage.py migrate --settings=yourthoughts.production_settings &&
               python manage.py runserver 0.0.0.0:8000 --settings=yourthoughts.production_settings"
      depends_on:
      - db
    logging:
      driver: "json-file"
      options:
        max-size: "10k"
        max-file: "3"


#  web:
#      build: ./backend
#      command: python manage.py runserver 0.0.0.0:8000
#      volumes:
#        - ./backend:/code
#      ports:
#        - 8000:8000
#      depends_on:
#        - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "10001:3000"
    restart: 'always'
    logging:
      driver: "json-file"
      options:
        max-size: "10k"
        max-file: "3"
#    volumes:
#      - ./frontend:/app
#      - /app/node_modules
#    ports:
#      - 3000:3000
#    environment:
#      - NODE_ENV=development