# Generated by Django 4.2.7 on 2024-01-23 23:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moduleName', models.CharField(max_length=50)),
                ('materialQuestion', models.CharField(max_length=200)),
                ('lecturerQuestion', models.CharField(max_length=200)),
                ('materialRating', models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(5)])),
                ('materialFeedback', models.CharField(max_length=500, null=True)),
                ('lecturerRating', models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(5)])),
                ('lecturerFeedback', models.CharField(max_length=500, null=True)),
                ('submitDate', models.DateTimeField(auto_now_add=True)),
                ('academicYear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.academicyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.student')),
            ],
        ),
    ]
