# Generated by Django 4.2.7 on 2024-01-23 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='lecturerFeedback',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='materialFeedback',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
