# Generated by Django 4.2.7 on 2024-02-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='title',
            field=models.CharField(max_length=70),
        ),
    ]
