# Generated by Django 4.2.7 on 2024-02-13 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_rename_user_student_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student',
            new_name='user',
        ),
    ]
