# Generated by Django 4.2.7 on 2024-02-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_alter_module_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='lecturerFeedback',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='materialFeedback',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
