# Generated by Django 4.2.7 on 2024-02-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_alter_feedback_lecturerfeedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='lecturerFeedback',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='materialFeedback',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
