# Generated by Django 4.2.7 on 2024-02-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_alter_feedback_lecturerfeedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='lecturersName',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
