# Generated by Django 4.2.7 on 2024-03-01 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_rename_lecturersname_module_lecturersnames'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.student'),
        ),
    ]
