# Generated by Django 4.2.7 on 2024-03-03 00:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0007_alter_feedback_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='assessmentFeedback',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='assessmentRating',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
