# Generated by Django 4.2.7 on 2024-04-07 12:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0009_alter_feedback_assessmentrating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicyear',
            name='year',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(2010), django.core.validators.MaxValueValidator(2040)]),
        ),
    ]
